sudo: required
services:
  - docker

before_install:
  - docker build -t jojointh/docker-react -f Dockerfile.dev .

script:
  - docker run jojointh/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "Docker React2"
  env: "DockerReact2-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-195609702756"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"